database:
  type: sqlite

  sqlite:
    file: sqlite.db
# pa los que no entienden ps
  mysql:
    host: 127.0.0.1
    username: root
    password: "la password de tu database"
    schema: "el nombre de la database "
  worker-limit: 1

